# Generated by Django 4.1.7 on 2023-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_employees', models.IntegerField()),
                ('security', models.BooleanField()),
                ('nr_customers', models.IntegerField()),
                ('pharmacy_name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
            ],
        ),
    ]
